# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('type', models.CharField(max_length=30, verbose_name='Type')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=3)),
                ('row', models.CharField(max_length=3)),
                ('sat', models.CharField(choices=[('L8', 'Landsat 8'), ('L7', 'Landsat 7'), ('L5', 'Landsat 5')], max_length=50, verbose_name='Satellite')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=21, unique=True, verbose_name='Name')),
                ('cloud_rate', models.FloatField(blank=True, null=True, verbose_name='Cloud Rate')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('created', 'Created'), ('downloading', 'Downloading'), ('dl_failed', 'Download Failed'), ('downloaded', 'Downloaded'), ('processing', 'Processing'), ('p_failed', 'Processing Failed'), ('processed', 'Processed')], max_length=50)),
            ],
            options={
                'ordering': ['-date', 'path', 'row'],
                'verbose_name': 'Scene',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landsat_uploader.Scene'),
        ),
    ]
