# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsat_uploader', '0002_auto_20170522_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandsatGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.IntegerField()),
                ('row', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
