# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landsat_uploader', '0003_landsatgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landsatgrade',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
