# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsat_uploader', '0004_auto_20170523_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
