# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landsat_uploader', '0005_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='scene',
        ),
        migrations.DeleteModel(
            name='LandsatGrade',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
    ]
